---

passwordAdmin:
  name: passwordAdmin
  line_type: simple
  arg: string
password:
  name: password
  line_type: simple
  arg: string
serverCommandPassword:
  name: serverCommandPassword
  line_type: simple
  arg: string
hostname:
  name: hostname
  line_type: simple
  arg: string
maxPlayers:
  name: maxPlayers
  line_type: simple
  arg: integer
motd:
  name: motd
  line_type: list
  arg: string
admins:
  name: admins
  line_type: list
  arg: string
headlessClients:
  name: headlessClients
  line_type: list
  arg: address
localClient:
  name: localClient
  line_type: list
  arg: address
voteTheshold:
  name: voteTheshold
  line_type: simple
  arg: integer
voteMissionPlayers:
  name: voteMissionPlayers
  line_type: simple
  arg: integer
allowVoteCmds:
  name: allowVoteCmds
  line_type: list
  arg: string
allowVotedAdminCmds:
  name: allowVotedAdminCmds
  line_type: list
  arg: string
kickduplicate:
  name: kickduplicate
  line_type: simple
  arg: integer
loopback:
  name: loopback
  line_type: simple
  arg: bool
upnp:
  name: upnp
  line_type: simple
  arg: bool
allowedFilePatching:
  name: allowedFilePatching
  line_type: simple
  arg: integer
allowedLoadFileExtensions:
  name: allowedLoadFileExtensions
  line_type: list
  arg: string
allowedPreprocessFileExtensions:
  name: allowedPreprocessFileExtensions
  line_type: list
  arg: string
allowedHTMLLoadExtensions:
  name: allowedHTMLLoadExtensions
  line_type: list
  arg: string
allowedHTMLLoadURIs:
  name: allowedHTMLLoadURIs
  line_type: list
  arg: string
filePatchingExceptions:
  name: filePatchingExceptions
  line_type: list
  arg: string
disconnectTimeout:
  name: disconnectTimeout
  line_type: simple
  arg: integer
maxdesync:
  name: maxdesync
  line_type: simple
  arg: integer
maxping:
  name: maxping
  line_type: simple
  arg: integer
maxpacketloss:
  name: maxpacketloss
  line_type: simple
  arg: integer
kickClientsOnSlowNetwork:
  name: kickClientsOnSlowNetwork
  line_type: list
  arg: integer
enablePlayerDiag:
  name: enablePlayerDiag
  line_type: simple
  arg: integer
callExtReportLimit:
  name: callExtReportLimit
  line_type: simple
  arg: integer
kickTimeout:
  name: kickTimeout
  line_type: list
  arg: integer
votingTimeOut:
  name: votingTimeOut
  line_type: simple
  arg: integer
roleTimeOut:
  name: roleTimeOut
  line_type: list
  arg: integer
briefingTimeOut:
  name: briefingTimeOut
  line_type: list
  arg: integer
debriefingTimeOut:
  name: debriefingTimeOut
  line_type: list
  arg: integer
lobbyIdleTimeout:
  name: lobbyIdleTimeout
  line_type: simple
  arg: integer
missionsToServerRestart:
  name: missionsToServerRestart
  line_type: simple
  arg: integer
missionsToShutdown:
  name: missionsToShutdown
  line_type: simple
  arg: integer
autoSelectMission:
  name: autoSelectMission
  line_type: simple
  arg: bool
randomMissionOrder:
  name: randomMissionOrder
  line_type: simple
  arg: bool
disableChannels:
  name: disableChannels
  line_type: list
  arg: integer
verifySignatures:
  name: verifySignatures
  line_type: simple
  arg: integer
drawingInMap:
  name: drawingInMap
  line_type: simple
  arg: bool
disableVoN:
  name: disableVoN
  line_type: simple
  arg: integer
vonCodecQuality:
  name: vonCodecQuality
  line_type: simple
  arg: integer
vonCodec:
  name: vonCodec
  line_type: simple
  arg: integer
skipLobby:
  name: skipLobby
  line_type: simple
  arg: bool
allowProfileGlasses:
  name: allowProfileGlasses
  line_type: simple
  arg: bool
zeusCompositionScriptLevel:
  name: zeusCompositionScriptLevel
  line_type: simple
  arg: integer
logFile:
  name: logFile
  line_type: simple
  arg: string
doubleIdDetected:
  name: doubleIdDetected
  line_type: simple
  arg: command
onUserConnected:
  name: onUserConnected
  line_type: simple
  arg: command
onUserDisconnected:
  name: onUserDisconnected
  line_type: simple
  arg: command
onHackedData:
  name: onHackedData
  line_type: simple
  arg: command
onDifferentData:
  name: onDifferentData
  line_type: simple
  arg: command
onUnsignedData:
  name: onUnsignedData
  line_type: simple
  arg: command
onUserKicked:
  name: onUserKicked
  line_type: simple
  arg: command
regularCheck:
  name: regularCheck
  line_type: simple
  arg: command
BattlEye:
  name: BattlEye
  line_type: simple
  arg: integer
timeStampFormat:
  name: timeStampFormat
  line_type: simple
  arg: string
forceRotorLibSimulation:
  name: forceRotorLibSimulation
  line_type: simple
  arg: integer
persistent:
  name: persistent
  line_type: simple
  arg: integer
requiredBuild:
  name: requiredBuild
  line_type: simple
  arg: float
statisticsEnabled:
  name: statisticsEnabled
  line_type: simple
  arg: integer
forcedDifficulty:
  name: forcedDifficulty
  line_type: simple
  arg: string
steamProtocolMaxDataSize:
  name: steamProtocolMaxDataSize
  line_type: simple
  arg: integer
armaUnitsTimeout:
  name: armaUnitsTimeout
  line_type: simple
  arg: integer
missionWhitelist:
  name: missionWhitelist
  line_type: list
  arg: string
Missions:
  name: Missions
  line_type: missions
  arg: object
MPMissions:
  name: MPMissions
  line_type: mpmissions
  arg: object
params:
  name: params
  line_type: params
  arg: object
